//
// Created by wint3rmute on 3/6/18.
//

#ifndef PROJECT_CONSTANTS_H
#define PROJECT_CONSTANTS_H


#define GAME_WINDOW_HEIGHT 1000
#define GAME_WINDOW_WIDTH 1600


#define FRAME_TIME 1.0/60.0

#define PLANE_SPEED 2
#define ACCELERATION_MULTIPLIER 0.03
#define MAX_SPEED 7
#define MIN_SPEED 1

#define DEG_2_RAD 0.0174532925
#define ROTATION_SPEED 1



#define BULLET_SPEED 7
#define BULLET_SIZE 3.f

#define PISTOL_AMMO 8
#define PISTOL_COOLDOWN_TIME 4.5f
#define TELEPORTATION_TRIGGER_OFFSET 20

#endif //PROJECT_CONSTANTS_H
